# -*- coding: utf-8 -*-
"""Activation Engineering, Turner et al_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZeB3gLgqsyF8-r2oXuGFE8bxVHqOW23

# **ActAdd(Activation Addition) method** - "Love vs. Hate" Steering Experiment.

# - It attempts to answer the scientific question: Can we surgically remove "hate" from a model's thought process and replace it with "love," even if the user explicitly asks it to be hateful?
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install transformer_lens

import torch
from transformer_lens import HookedTransformer
from typing import Dict, Union, List

torch.set_grad_enabled(False)
model = HookedTransformer.from_pretrained("gpt2-xl")
model.eval()
if torch.cuda.is_available():
    model.to("cuda")

SEED = 0
sampling_kwargs = dict(temperature=1.0, top_p=0.3, freq_penalty=1.0)

# Specific to love/hate example
prompt_add, prompt_sub = "Love", "Hate"
coeff = 5
act_name = 6
prompt = "I hate you because"

# Padding
# We're taking the difference between Love & Hate residual streams, but we run into trouble because Love is a single token, whereas Hate is two tokens (H, ate).
# We solve this by right-padding Love with spaces until it's the same length as Hate. I've done this generically below, but conceptually it isn't important.
# (PS: We tried padding by model.tokenizer.eos_token and got worse results compared to spaces. We don't know why this is yet.)
tlen = lambda prompt: model.to_tokens(prompt).shape[1]
pad_right = lambda prompt, length: prompt + " " * (length - tlen(prompt))
l = max(tlen(prompt_add), tlen(prompt_sub))
prompt_add, prompt_sub = pad_right(prompt_add, l), pad_right(prompt_sub, l)
print(f"'{prompt_add}'", f"'{prompt_sub}'")

# Getting activations before adding hooks
# Hook residual pre(resid_pre)
def get_resid_pre(prompt: str, layer: int):
    name = f"blocks.{layer}.hook_resid_pre"
    cache, caching_hooks, _ = model.get_caching_hooks(lambda n: n == name)
    with model.hooks(fwd_hooks = caching_hooks):
        _ = model(prompt)
    return cache[name]

act_add = get_resid_pre(prompt_add, act_name)
act_sub = get_resid_pre(prompt_sub, act_name)
act_diff = act_add - act_sub
print(act_diff.shape)


# ACTIVATION VECTOR HOOK(ave)
def ave_hook(resid_pre, hook):
    if resid_pre.shape[1] == 1:
        return

    # We only add to the prompt (first call), not to the every generated token
    # ppop, apos = prompt position, activation position(Basically no of tokens in prompt and steering vector)
    ppos, apos = resid_pre.shape[1], act_diff.shape[1]
    assert apos <= ppos, f"More modification tokens ({apos}) then prompt tokens ({ppos})!"
    # add to the beginning (position-wise) of the activations
    resid_pre[:, :apos, :] += coeff * act_diff


# HOOKED GENERATION
def hooked_generate(prompt_batch: List[str], fwd_hooks=[], seed=None, **kwargs):
    if seed is not None:
        torch.manual_seed(seed)
    with model.hooks(fwd_hooks=fwd_hooks):
        tokenized = model.to_tokens(prompt_batch)
        r = model.generate(input=tokenized, max_new_tokens = 50, do_sample=True, **kwargs)
    return r

editing_hooks = [(f"blocks.{act_name}.hook_resid_pre", ave_hook)]
res = hooked_generate([prompt] * 4, editing_hooks, seed=SEED, **sampling_kwargs)

# Print results, removing the ugly beginning of sequence token
res_str = model.to_string(res[:, 1:])
print(("\n\n" + "-" * 80 + "\n\n").join(res_str))